require('andrewmcdonough.plugins-setup')
require('andrewmcdonough.core.keymaps')
require('andrewmcdonough.core.options')
require('andrewmcdonough.core.colorscheme')
require('andrewmcdonough.plugins.nvim-tree')
require('andrewmcdonough.plugins.telescope')
require('andrewmcdonough.plugins.mason')
