require('andrewmcdonough.plugins-setup')
require('andrewmcdonough.core.keymaps')
require('andrewmcdonough.core.options')
require('andrewmcdonough.core.colorscheme')
-- require('andrewmcdonough.plugins.nvim-tree')
require('andrewmcdonough.plugins.telescope')
require('andrewmcdonough.plugins.mason')
require('andrewmcdonough.plugins.gitsigns')
require('andrewmcdonough.plugins.which-key')
require('andrewmcdonough.plugins.lualine')
require('andrewmcdonough.plugins.nvim-cmp')
require('andrewmcdonough.plugins.ale')
require('andrewmcdonough.plugins.lsp')
require('andrewmcdonough.functions.ruby')
require('andrewmcdonough.functions.nvim')
